name: Get Custom Token

on:
  push:
    branches:
      - main

jobs:
  get_token:
    runs-on: ubuntu-latest
    steps:
      - name: Get Custom Token
        id: custom_token
        run: |
          echo "Custom Token: ${{secrets.MY_CUSTOM_TOKEN}}"
          echo "MY_CUSTOM_TOKEN=${{secrets.MY_CUSTOM_TOKEN}}" >> $GITHUB_ENV"

      - name: Inject Custom Token into HTML
        run: |
          sed -i "s/{{MY_CUSTOM_TOKEN}}/${{ secrets.MY_CUSTOM_TOKEN }}/g" index.html

