name: Get GitHub Token

on:
  push:
    branches:
      - main

jobs:
  get_token:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub Token
        id: github_token
        run: |
          echo "GitHub Token: ${{secrets.GITHUB_TOKEN}}"
          echo "GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}" >> $GITHUB_ENV
