name: Update Repos JSON

on:
  push:                # Executa a cada commit
  workflow_dispatch:   # Permite execução manual

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Buscar repositórios via API GitHub
        run: |
          curl -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}" \
               https://api.github.com/users/WesleyS08/repos?per_page=100 \
               | jq '.' > repos.json

      - name: Commit e push do arquivo JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/WesleyS08/my-portfolio2.git
          git add repos.json
          git commit -m "Atualiza lista de repositórios" || echo "Sem alterações"
          git push
