name: Update Repos JSON

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Verificar se token está definido
        run: |
          if [ -z "${{ secrets.PERSONAL_TOKEN }}" ]; then
            echo "O token NÃO está definido!"
            exit 1
          else
            echo "O token está definido."
          fi

      - name: Buscar repositórios via API GitHub e salvar JSON
        run: |
          curl -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}" \
               "https://api.github.com/users/WesleyS08/repos?per_page=100" \
               > repos.json

          # Listar nomes no log
          cat repos.json | jq -r '.[].name'

      - name: Calcular porcentagem de linguagens em todos os repositórios
        run: |
          set -euo pipefail
          IFS=$'\n\t'

          repos=$(jq -r '.[].name' repos.json)
          declare -A lang_bytes

          for repo in $repos; do
            echo "Processando repo: $repo"
            langs=$(curl -s -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}" "https://api.github.com/repos/WesleyS08/$repo/languages" | jq -r 'to_entries|map("\(.key) \(.value)")|.[]')

            if [[ -z "$langs" ]]; then
              echo "Nenhuma linguagem encontrada para $repo"
              continue
            fi

            while read -r lang bytes; do
              if [[ -n "$lang" ]]; then
                lang_bytes[$lang]=$(( ${lang_bytes[$lang]:-0} + bytes ))
              fi
            done <<< "$langs"
          done

          total=0
          for v in "${lang_bytes[@]}"; do
            total=$(( total + v ))
          done

          echo "Porcentagem geral de linguagens:" > languages.json
          for lang in "${!lang_bytes[@]}"; do
            percent=$(echo "scale=2; ${lang_bytes[$lang]} * 100 / $total" | bc)
            echo "$lang: $percent%" >> languages.json
            echo "$lang: $percent%"
          done

      - name: Configurar Git para push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/WesleyS08/my-portfolio2.git

      - name: Commit e push do arquivo JSON
        run: |
          git add repos.json languages.json
          git commit -m "Atualiza lista de repositórios e porcentagem de linguagens" || echo "Sem alterações para commitar"
          git push origin main
