name: Update Repos JSON

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Verificar se token está definido
        run: |
          if [ -z "${{ secrets.PERSONAL_TOKEN }}" ]; then
            echo "O token NÃO está definido!"
            exit 1
          else
            echo "O token está definido."
          fi

      - name: Buscar repositórios via API GitHub e listar nomes
        run: |
          curl -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}" \
               "https://api.github.com/users/WesleyS08/repos?per_page=100" \
               > repos.json

          # Extrair e imprimir no log os nomes dos repositórios
          cat repos.json | jq -r '.[].name'
